ccms:
  url: https://gateway.ftlapp.io/api/ccms
  headers:
    api-key: apiF6LvC1ICF7b5UK12zPm7mMr7Uzf4S
    Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNjgiLCJyb2xlcyI6IlJPTEVfQ0NNU19ST09UIiwidXNlcm5hbWUiOiJjY21zIiwidHlwZSI6IlJPT1QiLCJncm91cCI6IlJPT1QiLCJvd25lciI6IlJPT1QiLCJsYW5ndWFnZSI6ImNuIiwidmVyc2lvbiI6InYxLjIuMSIsInRva2VuVHlwZSI6IkFQUCIsImFwcCI6IkN3bUNmcDJQUkFHT0JTTkpKVWpyZ1VKT1gyWlBKc2ljIiwianRpIjoiNzQ0NDFjZWY4MGI3NGY3Y2FkMGQ2YjBjNTU5NzEzMmEifQ.jfBaKe2f3om-ux6FbkcrOjJFXyuXsDjkOEYb3QZnFNwT6dW30XFG4Hunr29Px6Av8woEdcud8u25zKPxr_4mDA

