export enum RestrictionTypeEnum {
  FR_MILITARY_ADDRESS = 'FR_MILITARY_ADDRESS', //(法邮军事地址校验）
  FR_OVERSEAS_TERRITORY = 'FR_OVERSEAS_TERRITORY', //（法邮海外省校验）
  COLISSIMO_FR_6A_ZONE = 'COLISSIMO_FR_6A_ZONE', //（法邮城市邮编校验）
  COLISPRIVE_FR_ALLOWED_POSTAL_CODE = 'COLISPRIVE_FR_ALLOWED_POSTAL_CODE', //（CP的邮编库校验）
  GLS_IT_BLACKLIST_AREA = 'GLS_IT_BLACKLIST_AREA', //(GLS,IT黑名单）
  GLS_PT_BLACKLIST_AREA = 'GLS_PT_BLACKLIST_AREA', //(GLS,PT黑名单）
  GLS_GR_BLACKLIST_AREA = 'GLS_GR_BLACKLIST_AREA', //(GLS,GR黑名单）
  GLS_GB_BLACKLIST_AREA = 'GLS_GB_BLACKLIST_AREA', //(GLS,GB黑名单）
  GLS_ES_BLACKLIST_AREA = 'GLS_ES_BLACKLIST_AREA', //(GLS,ES黑名单）
  RANDOM_EMAIL_FOR_SENDER = 'RANDOM_EMAIL_FOR_SENDER', // 寄件随机邮编
}
