export const ShipmentAddress = {
  FR: {
    city: 'paris',
    comment: '',
    company: 'X sociale',
    countryCode: 'FR',
    email: 'ddd@ggla.com',
    firstName: 'firstS',
    lastName: 'lastS',
    mobileNumber: '0659969984',
    phoneNumber: '0659969984',
    postalCode: '75018',
    street1: 'sender street address 1 ds',
    street2: 'sender street address 2 ds',
    street3: 'sender street address 3 ds',
  },
  BE: {
    lastName: 'Embassy of China in Belgium',
    phoneNumber: '26633001',
    street1: 'Avenue de Tervueren 439',
    postalCode: '1150',
    city: 'Brussel',
    countryCode: 'BE',
    company: 'WZ Company',
  },
  CH: {
    lastName: 'Lion Monument',
    phoneNumber: '412271717',
    street1: 'Denkmalstrasse 4',
    postalCode: '6002',
    city: 'Luzern',
    countryCode: 'CH',
    company: 'WZ Company',
  },
  DE: {
    lastName: 'A&O Berlin Mitte',
    phoneNumber: '30809475200',
    street1: 'Köpenicker Str. 127-129',
    postalCode: '10179',
    city: 'Berlin',
    countryCode: 'DE',
    company: 'WZ Company',
  },
  ES: {
    lastName: 'Correos CTA',
    phoneNumber: '34915963183',
    street1: 'Camino Hormigueras 169',
    postalCode: '28031',
    city: 'Madrid',
    province: 'Madrid',
    countryCode: 'ES',
    company: 'WZ Company',
    comment: '',
    email: 'ddd@ggla.com',
    firstName: 'firstS',
    mobileNumber: '0659969984',
    street2: 'sender street address 2 ds',
    street3: 'sender street address 3 ds',
  },
  GB: {
    lastName: 'Palace of Westminster',
    phoneNumber: '2072193000',
    street1: '10 Downing Street',
    postalCode: 'SW1A 0AA',
    city: 'London',
    countryCode: 'GB',
    company: 'WZ Company',
  },
  GF: {
    lastName: 'French Guiana',
    phoneNumber: '00592-2254297',
    street1: '1 Avenue Auguste Boudinot',
    postalCode: '97310',
    city: 'Kourou',
    countryCode: 'GF',
    company: 'WZ Company',
  },
  IT: {
    lastName: 'Viale del Policlinico',
    phoneNumber: '0642740571',
    street1: 'Viale del Policlinico,155',
    postalCode: '00161',
    city: 'Roma',
    countryCode: 'IT',
    company: 'WZ Company',
  },
  NL: {
    lastName: 'Embassy of China in Netherlands',
    phoneNumber: '703065061',
    street1: 'Willem Lodewijklaan 10',
    postalCode: '2517',
    city: 'Den Haag',
    countryCode: 'NL',
    company: 'WZ Company',
  },
  SE: {
    lastName: 'Embassy of China in Sweden',
    phoneNumber: '760174441',
    street1: 'Djurgårdsbrunnsvägen 40',
    postalCode: '11527',
    city: 'Stockholm',
    countryCode: 'SE',
    company: 'WZ Company',
  },
  KH: {
    province: 'Phnom Penh',
    city: 'PORSENCHEY',
    comment: '',
    company: '',
    countryCode: 'KH',
    email: '',
    firstName: 'KIMPEOU THANVUTHY',
    lastName: '',
    mobileNumber: '070893436',
    phoneNumber: '070893436',
    postalCode: '12511',
    street1: '#12 street01,borey piphup thmey 1,',
    street2: 'NR3,Sangkat Pleurn Chhes Rotes,',
    street3: 'Khan Kombol',
  },
};
