export enum Transporter {
  'GLS' = 'GLS',
  'GLS_ES' = 'GLS_ES',
  'UPS' = 'UPS',
  'GLS_V2' = 'GLS_V2',
  'ALGERIA' = 'ALGERIA',
  'CAINIAO' = 'CAINIAO',
  'ESPOST' = 'ESPOST',
  'COLICOLI' = 'COLICOLI',
  'DELIVENGO' = 'DELIVENGO',
  'MONDIAL_RELAY' = 'MONDIAL_RELAY',
  'GEODIS' = 'GEODIS',
  'SF' = 'SF',
  'EXP' = 'EXP',
  'DHL' = 'DHL',
  'CHRONOPOST' = 'CHRONOPOST',
  'ASENDIA' = 'ASENDIA',
  'CORREOS' = 'CORREOS',
  'DPD' = 'DPD',
  'COLISSIMO' = 'COLISSIMO',
  'BE' = 'BE',
  'FEDEX' = 'FEDEX',
  'DPD_CN' = 'DPD_CN',
  'XBS' = 'XBS',
  'COLISPRIVE' = 'COLISPRIVE',
  'CTT' = 'CTT',
  'BOYACA' = 'BOYACA',
  'CMS_TRACK' = 'CMS_TRACK',
  'PAACK' = 'PAACK',
  'ZTO' = 'ZTO',
  'CAINIAO_V2' = 'CAINIAO_V2',
  'AMAZON' = 'AMAZON',
  'DISPEO' = 'DISPEO',
  'GPX' = 'GPX',
  'CRONO' = 'CRONO',
}

export enum LastmileProvider {
  'ALGERIA' = 'ALGERIA',
  'AMAZON' = 'AMAZON',
  'ASENDIA' = 'ASENDIA',
  'BE' = 'BE',
  'BOYACA' = 'BOYACA',
  'CHRONOPOST' = 'CHRONOPOST',
  'COLICOLI' = 'COLICOLI',
  'COLISPRIVE' = 'COLISPRIVE',
  'COLISSIMO' = 'COLISSIMO',
  'CORREOS' = 'CORREOS',
  'CRONO' = 'CRONO',
  'CTT' = 'CTT',
  'DELIVENGO' = 'DELIVENGO',
  'DHL' = 'DHL',
  'DPD' = 'DPD',
  'DPD_CN' = 'DPD_CN',
  'ESPOST' = 'ESPOST',
  'EXP' = 'EXP',
  'FEDEX' = 'FEDEX',
  'GEODIS' = 'GEODIS',
  'GLS' = 'GLS',
  'GPX' = 'GPX',
  'MONDIAL_RELAY' = 'MONDIAL_RELAY',
  'PAACK' = 'PAACK',
  'SF' = 'SF',
  'UNKNOWN' = 'UNKNOWN',
  'UPS' = 'UPS',
  'XBS' = 'XBS',
  'ZTO' = 'ZTO',
}

export enum ParcelStatus {
  'UNKNOWN' = 'UNKNOWN',
  'CREATED' = 'CREATED',
  'BEFORE_TRANSIT' = 'BEFORE_TRANSIT', // 未上网
  'DELIVERING' = 'DELIVERING',
  'RETURNED' = 'RETURNED',
  'ARRIVED' = 'ARRIVED',
  'APPOINTED' = 'APPOINTED',
  'STOPPED' = 'STOPPED',
  'LOST' = 'LOST',
  'DELETED' = 'DELETED',
  'REMAINING' = 'REMAINING', // 维持不变
}

export enum Language {
  'FR' = 'FR',
  'EN' = 'EN',
  'CN' = 'CN',
}
