GET http://localhost:3003/api/cms/parcel/5P000000132660000/trackings
Content-Type: application/json;charset=UTF-8
api-key: CMS
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1NTIiLCJyb2xlcyI6IlJPTEVfQ01TX0FQUCIsInVzZXJuYW1lIjoiZXNlbmRlb19hcHAiLCJ0eXBlIjoiQ0xJRU5UIiwiZ3JvdXAiOiJFU0VOREVPIiwib3duZXIiOiJFU0VOREVPIiwibGFuZ3VhZ2UiOiJjbiIsInZlcnNpb24iOiJ2MS4xIiwidG9rZW5UeXBlIjoiQ0xJRU5UIiwiYXBwIjoiODY4MWRjMzEtYTUzZS00Y2JkLWEyMjYtMWNkZmMxNzMzYTM2IiwianRpIjoiZTkwNTFlYWIyMWFhNDk4NzljMjYyMmM4ZmEzYWFjYjgifQ.jBrB_8CXF7ZJP3DkpHnl5Cfc_wc25MuhTNZSnkyrk4eRO0CFf-NNvCarHSA9OMz4wCONGe61cCvGxJGqASYUNA

###

